# Generated by Django 3.2.2 on 2023-10-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='bought_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wished_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table=None,
        ),
    ]
